### ISSUE TITLE
Issues with the new version of the NG CLI

### ISSUE THREAD

**Issue by rvmladenov** [meeroslav/localize-router-example#2]
I had some issues with the new version of the NG CLI. To fix it I made the following updates:

"devDependencies": {
    "@angular/cli": "1.0.0-beta.30",
    "@angular/compiler-cli": "^2.3.1",

**Comment by meeroslav** [comment]
@rvmladenov What were the issues?

**Comment by sarath704** [comment]
I am working with angular 5.1.X i am getting following error

```
/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:692
var LOCALIZE_ROUTER_FORROOT_GUARD = new __WEBPACK_IMPORTED_MODULE_0__angular_core__["OpaqueToken"]('LOCALIZE_ROUTER_FORROOT_GUARD');
                                    ^

TypeError: __WEBPACK_IMPORTED_MODULE_0__angular_core__.OpaqueToken is not a constructor
    at Object.module.exports (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:692:37)
    at __webpack_require__ (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:30:30)
    at Object.<anonymous> (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:260:82)
    at __webpack_require__ (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:30:30)
    at Object.module.exports (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:98:82)
    at __webpack_require__ (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:30:30)
    at Object.module.exports (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:961:83)
    at __webpack_require__ (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:30:30)
    at Object.<anonymous> (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:930:86)
    at __webpack_require__ (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:30:30)
```
